### PR TITLE
Bugfix: Grid View Display in New Window

### LINKED ISSUE #115: Display Grid View in New Window Stops Working
The functionality to display grid view in a new window (implemented in #69) stops working. The opened window stays blank and won't load the grid view. It appears that the new window fails to receive the message from the main window.

It is suspected to be caused by asynchronous import of `AppModule` (implemented in #103). Specifically, the main window waits for the `DOMContentLoaded` event of the new window and then send the message. Because `AppModule` is now imported asynchronously, `DOMContentLoaded` could no longer guarantee that the new window has registered the event listener of the `message` event.

Suggested fix would be letting the new window initiates the data exchange process by posting a message to the main window, and then the main window could reply with serialized data.

### PR DESCRIPTION
**Pull request by yongkanm**
### Description

This pull request fixes the bug that displaying grid view in new window stops working (#115). The fix suggested in the issue (also included below) is applied.

    Suggested fix would be letting the new window initiates the data exchange process by posting a message to the main window, and then the main window could reply with serialized data.

### Testing Note

Please test if the feature of displaying grid view in new window functions as described in #69.

### CODE REVIEW

**Review by epsilonError — CHANGES_REQUESTED** [review]
Couldn't get new window to populate grid view when using `token-atm-app`.

Once I got a Segmentation Fault when closing the pop-up window.
More consistently the window contained nothing and the server/console reported `"GET /grid-view" Error (404): "Not found"`

**Comment by yongkanm** [comment]
> Couldn't get new window to populate grid view when using `token-atm-app`.
> 
> Once I got a Segmentation Fault when closing the pop-up window. More consistently the window contained nothing and the server/console reported `"GET /grid-view" Error (404): "Not found"`

Could not reproduce on my end. Please try the following steps and see if the issue persists:

1. Test it with the development server of Angular (i.e., `ng serve`). Please inspect the page and check if there is a `app-grid-view-external-access` element under the `app-root` element. If so, then Angular is loaded, and the routing is functioning.
2. Test it with production build. Please note that after the production build is generated, `cp dist/token-atm-spa/index.html dist/token-atm-spa/404.html` needs to be executed (done at line 47 in `.github/workflows/ci_cd.yml`). This is because the statically-hosted Token ATM will not handle routing as the Angular development server does. Also, the webserver used to host the production build needs to have the ability to respond with 404.html when a route does not match. An 404 error is actually expected to occur since `404.html` is now playing the role of `index.html` to load Token ATM. Under the production build, please also inspect the page and check if `app-grid-view-external-access` presents.

By the way, I don't think the segmentation fault is relevant to this issue. It is possibly related to DevTools (I've encountered the freeze & crash of `token-atm-app` several times after I opened the DevTools, and I believe it is an Electron issue).

**Comment by epsilonError** [comment]
I don't see `app-grid-view-external-access` as an html element or as text in the page for either the development or production build.

**Comment by yongkanm** [comment]
> I don't see `app-grid-view-external-access` as an html element or as text in the page for either the development or production build.

Can you find the `app-root` element? If not, then Angular is not loaded, which means that the webserver you used does not support responding with `404.html` in the case of route mismatch.

**Review by epsilonError — APPROVED** [review]
Got the grid view to work for the development build.

Looks good to me.

**Pull request merged**
