### PR TITLE
Feature & Enhancement & Bugfix & Refactoring: Various update about FormField

### LINKED ISSUE #63: Too Easy to Change Time for Date Field in Token Option in Accident
The user reports that it's too easy to accidentally change the time for date field in the token option. It could be caused by the ability to change time by scrolling the mouse wheel or clicking the spinner.

### PR DESCRIPTION
**Pull request by yongkanm**
#### Feature

The end date and new due date of token option with the type of spending for assignment resubmission now supports configuring exceptions for different sections.

#### Enhancement

1. To fix #63, the ability to change time in the date field of token option by scrolling mouse wheel, clicking spinners, and pressing arrow keys has been disabled. Also, the spinners are hidden.
2. `console.error` is used for reporting errors when Angular is running in development mode in order to simplify debugging.

#### Bugfix

This pull request fixes an issue of not persisting token option group's name & description after modification.

#### Refactoring

The implementation of the following UI components has been modified:

1. The modal to create Token ATM configuration
2. The modal to edit Token ATM configuration metadata
3. The modal to create & edit token option group
4. The modal to create & edit token options

### Testing Note

Please test if feature & enhancement & bugfix mentioned above works as described. For refactoring, please test if UI components mentioned above still work as expected. Specifically, the creation and modification of all types of token options should be tested.

### CODE REVIEW

**Comment by yongkanm** [comment]
> ### _Testing Failure_ for Creation of `Withdraw Lab Data Request` token option
> Creation modal reports `Token option type invalid: should be 'Spend Tokens for Lab Data'` for a Withdraw Token Option ID that the canvas configuration page says is a `spend-for-lab-data` type.
> 
> Replication and More Info TBD

> ### _Testing Failure_ for Creation of `Withdraw Lab Switch Request (For Teacher Only)` token option
> Creation modal reports `Token option type invalid: should be 'Spend Tokens for Switching Lab'` for a Withdraw Token Option ID that the canvas configuration page says is a `spend-for-lab-switch` type.
> 
> Replication and More Info TBD

The bug has been identified: the validator accidentally used the withdraw token option type rather than the original token option type. Fix will be included in the next commit.

> <b>Note</b>: While replicating the the withdraw token option errors mentioned above, I found another edge case to be aware of.
> 
> If a quiz is created on canvas, and has never been published, Token ATM reports `Error: Invalid data` when trying to find the correct quiz via the user provided quiz name.
> 
> My guess is that this is because an unpublished quiz with no questions doesn't have a score (which is something we have come across before).
> 
> Upon further testing, a never published quiz that does have a point value assigned to it via a single scored question doesn't result in the `Error: Invalid data` inline report. So the uninitialized quiz score is likely the cause.

Confirmed using Canvas Live API that `points_possible` will be `null` in that case. The next commit will modify the serailization of `Quiz` object to accommodate this possibility.

**Comment by yongkanm** [comment]
> **Note**: While testing the options upon creation I encountered a strange edge case.
> 
> All the options are in one group. The first option is a basic request named `B`. The third option is Passing Canvas Module request also named `B`.
> 
> When the third Passing Canvas Module (`B`) is requested, Token ATM processes it as a basic request.

This behavior has been noticed before and is planned to be fixed later. Token ATM recognizes the token option being requested using the quiz answer, which is essentially "Request for" + the token option name. When two token options have the same name, the one that appears earlier in the token option group will be considered to be requested.

The fix is planned to be delivered along with the refactoring of token option creation & modification.

**Comment by yongkanm** [comment]
> ### _Testing Failure_ for UI Refactoring of Token Option Preview
> Creation of Token Options works correctly, and the Canvas configuration page matches what was saved. But upon previewing a token option's settings (read only state), the Token Balance Change field is shown as 0 in all Token Option Modals.
> 
> The actual current Token Balance Change in the Configuration is not reflected in the Token Option UI modal. (The 0 for Token Balance Change persists when clicking the edit button.)
> 
> After further testing, _this Failure only effects the UI view_ the underlying config data isn't changed unless the token option is edited and then saved.
> 
> This can lead to undesired changes though. Say a TA edits a token option, but doesn't notice that the Token Balance Change is now `0`. If the edits are saved without the `0` being corrected, then the canvas configuration will be modified an include that undesired change.

The bug has been identified: when passing in a token option to the FormField, the tokenBalanceChange isn't extracted. The fix will be included in the next commit.

**Comment by yongkanm** [comment]
> > Confirmed using Canvas Live API that `points_possible` will be `null` in that case. The next commit will modify the deserailization of `Quiz` object to accommodate this possibility.
> 
> Do we need to check that the any of the token options that use a grade threshold calculation, because null isn't a number?
> 
> Or should it be fine because the deserializer defaults it to 0. And once the quiz is actually published and complete-able by students it will have it's actual value then.

I believe it should be fine. Two relevant deserializers (`ModuleItemInfo` and `Quiz`) both consider `point_possible` to be `0` if it is a nullish value, so the request handler does not need to handle it as a special case.

**Comment by yongkanm** [comment]
> **Note**: Realized a possible edge case we'll need to handle in future. A deleted token option group, could have contained token options that are referenced by other other token options (e.g., as mutually exclusive, or for a request to withdraw).
> 
> The error handling at processing should prevent errors, but there is no warning or notice that such a break in functionality can/did happen.
> 
> I think this edge case (and others) could be helped by the `'Review Configuration'` future functionality we've talk about as a long-term goal.

Currently, all request handlers for token options with the type that refers to other token options is implemented in a defensive way, which means that an invalid token option id won't cause an issue. Specifically, if a withdrawal token option id is invalid, the request will be rejected. A invalid mutual exclusive token option id should not cause an issue since the check is performed by comparing token option id rather than the token option itself (This is an intentional design to accommodate for deleting token options).

However, it's correct that it will suppress the issue of invalid Token ATM configuration until the next time a user wants to modify it. Add the functionality to allow validating existing Token ATM configuration is a possible workaround.

**Comment by yongkanm** [comment]
> ### _Testing Failure_ for Due Date Modification
> `New Due Time for <Quiz Name>` was set to: `08/06/2023 23 : 59 : 58`
> 
> But Canvas reports new due time for the approved student as: `Aug 7 at 12:59am`.
> 
> Interestingly enough when the TA/Instructor goes into Canvas' Quiz editor and clicks on the assignment exception the formatted string is the same as the one reported above, but the interactive calendar selector has August **6th** highlighted. Though the time in the interactive selector also says `12:59am` rather than the desired `12:59pm`.
> 
> (I believe we've mentioned this Canvas interpretation before in-person, but I wanted to be sure to document it.)

Fails to reproduce on my side (the granted extension is `August 6 11:59 PM`, which is expected). We've encountered and documented such a behavior when timezone is inconsistent, and then we decide to ignore timezone issue for now. Please make sure the timezone of the system you're running Token ATM on, the timezone of Canvas personal profile, and the timezone of the Canvas course are consistent.

**Comment by yongkanm** [comment]
> > > ### _Testing Failure_ for Due Date Modification
> > > ...
> > 
> > 
> > Fails to reproduce on my side (the granted extension is `August 6 11:59 PM`, which is expected). We've encountered and documented such a behavior when timezone is inconsistent, and then we decide to ignore timezone issue for now. Please make sure the timezone of the system you're running Token ATM on, the timezone of Canvas personal profile, and the timezone of the Canvas course are consistent.
> 
> The timezones did not match between my systems. OS was Pacific, Canvas Profile was Mountain, and Canvas Course was Mountain.
> 
> After making them all match (Pacific time), the canvas interpretation worked as expected.
> 
> Does Electron have a simple way to check the OS timezone? And does Canvas provide API endpoints for checking Profile and Course timezones?
> 
> If so, we may want to add checking that the three match as part of the future audit/review/validate configuration functionality.

It's technically possible to add a check like that. For system timezone, the only concern is the timezone of the Date object, so we could use [`Date.prototype.getTimezoneOffset()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTimezoneOffset). Canvas also provide API endpoint to obtain timezone for both [course](https://canvas.instructure.com/doc/api/courses.html#method.courses.show) and [user](https://canvas.instructure.com/doc/api/users.html#method.profile.settings). However, both of these two API endpoints mark `time_zone` as an optional field, so an investigation of Canvas behavior is needed.

By the way, currently a check is added to the new due date field: any time between 00:00:00 and 00:00:59 will be considered as invalid.

**Review by epsilonError — APPROVED** [review]

**Pull request merged**
